AWSTemplateFormatVersion: '2010-09-09'
Description: 'PGA Code Test

  '
Globals:
  Function:
    Handler: app.lambdaHandler
    Runtime: nodejs8.10
    Timeout: 3
Resources:
  AWSUtilsLambdaLayer:
    Properties:
      CompatibleRuntimes:
      - nodejs8.10
      ContentUri: s3://pga.codetest.sls.package.bucket/c560977712cac824064462918a581bb0
      Description: Contains aws utils code used across lambdas
      LayerName: AWSUtilsLayer
      RetentionPolicy: Delete
    Type: AWS::Serverless::LayerVersion
  CommonCodeLambdaLayer:
    Properties:
      CompatibleRuntimes:
      - nodejs8.10
      ContentUri: s3://pga.codetest.sls.package.bucket/d91fb554304e2fca7700cb25b346562a
      Description: Contains common code used across lambdas
      LayerName: CommonCodeLayer
      RetentionPolicy: Delete
    Type: AWS::Serverless::LayerVersion
  CreatePlayerLambdaFunction:
    Properties:
      CodeUri: s3://pga.codetest.sls.package.bucket/fec4cdcd9a0e55f0a4f4ee4c2c78e1f8
      Events:
        CreatePlayer:
          Properties:
            Method: post
            Path: /players
          Type: Api
      Layers:
      - Ref: CommonCodeLambdaLayer
      - Ref: AWSUtilsLambdaLayer
      - Ref: DALLambdaLayer
      Policies:
      - S3CrudPolicy:
          BucketName: pga.players.db.bucket
    Type: AWS::Serverless::Function
  DALLambdaLayer:
    Properties:
      CompatibleRuntimes:
      - nodejs8.10
      ContentUri: s3://pga.codetest.sls.package.bucket/435deb376bdb4d1d1845f2d8ed7906ab
      Description: Contains data access layer code used across lambdas
      LayerName: DALLambdaLayer
      RetentionPolicy: Delete
    Type: AWS::Serverless::LayerVersion
  DeletePlayerLambdaFunction:
    Properties:
      CodeUri: s3://pga.codetest.sls.package.bucket/9b7a9d469af83f1232416b1a028f8019
      Events:
        DeleteThePlayer:
          Properties:
            Method: delete
            Path: /players/{player_id}
          Type: Api
      Layers:
      - Ref: CommonCodeLambdaLayer
      - Ref: AWSUtilsLambdaLayer
      - Ref: DALLambdaLayer
      Policies:
      - S3CrudPolicy:
          BucketName: pga.players.db.bucket
    Type: AWS::Serverless::Function
  GetPlayerLambdaFunction:
    Properties:
      CodeUri: s3://pga.codetest.sls.package.bucket/3c8da01e158253d57adc3712031b11fc
      Events:
        GetThePlayer:
          Properties:
            Method: get
            Path: /players/{player_id}
          Type: Api
      Layers:
      - Ref: CommonCodeLambdaLayer
      - Ref: AWSUtilsLambdaLayer
      - Ref: DALLambdaLayer
      Policies:
      - S3CrudPolicy:
          BucketName: pga.players.db.bucket
    Type: AWS::Serverless::Function
  ListAllPlayersLambdaFunction:
    Properties:
      CodeUri: s3://pga.codetest.sls.package.bucket/032f2985ee24953575ec8aff7c4c3e79
      Events:
        ListAllPlayers:
          Properties:
            Method: get
            Path: /players
          Type: Api
      Layers:
      - Ref: CommonCodeLambdaLayer
      - Ref: AWSUtilsLambdaLayer
      - Ref: DALLambdaLayer
      Policies:
      - S3CrudPolicy:
          BucketName: pga.players.db.bucket
    Type: AWS::Serverless::Function
  UpdatePlayerLambdaFunction:
    Properties:
      CodeUri: s3://pga.codetest.sls.package.bucket/70b54789fd3a0cabce2e1e0b43b98649
      Events:
        UpdateThePlayer:
          Properties:
            Method: put
            Path: /players/{player_id}
          Type: Api
      Layers:
      - Ref: CommonCodeLambdaLayer
      - Ref: AWSUtilsLambdaLayer
      - Ref: DALLambdaLayer
      Policies:
      - S3CrudPolicy:
          BucketName: pga.players.db.bucket
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
